### ISSUE TITLE
the example 'craco.config.js' not work

### ISSUE THREAD

**Issue by frru** [melMass/craco-raw-loader#2]
After I delete the webpack property, it work.

**Comment by Solo-Digital** [comment]
Yeah, it seems "plugins [...." goes outside the "webpack" object (if you have one in the config).

e.g.
`module.exports = {
  webpack: {
    alias: {
      "@": path.resolve(__dirname, "src/"),
    },
  },
  plugins: [
    {
      plugin: rawLoader,
      options: {
        test: /\.md$/i,
        exclude: /node_modules/,
      },
    },
  ],
};`

**Comment by melMass** [comment]
Should be solved by #1, don't hesitate to reopen if you have any other issues.
For some reason, I was not receiving any notifications from the repository.
